export const countries = [
  { name: "Afghanistan", code: "AF", phoneCode: "+93" },
  { name: "Albania", code: "AL", phoneCode: "+355" },
  { name: "Algeria", code: "DZ", phoneCode: "+213" },
  { name: "American Samoa", code: "AS", phoneCode: "+1-684" },
  { name: "Andorra", code: "AD", phoneCode: "+376" },
  { name: "Angola", code: "AO", phoneCode: "+244" },
  { name: "Anguilla", code: "AI", phoneCode: "+1-264" },
  { name: "Antarctica", code: "AQ", phoneCode: "+672" },
  { name: "Antigua and Barbuda", code: "AG", phoneCode: "+1-268" },
  { name: "Argentina", code: "AR", phoneCode: "+54" },
  { name: "Armenia", code: "AM", phoneCode: "+374" },
  { name: "Aruba", code: "AW", phoneCode: "+297" },
  { name: "Australia", code: "AU", phoneCode: "+61" },
  { name: "Austria", code: "AT", phoneCode: "+43" },
  { name: "Azerbaijan", code: "AZ", phoneCode: "+994" },
  { name: "Bahamas", code: "BS", phoneCode: "+1-242" },
  { name: "Bahrain", code: "BH", phoneCode: "+973" },
  { name: "Bangladesh", code: "BD", phoneCode: "+880" },
  { name: "Barbados", code: "BB", phoneCode: "+1-246" },
  { name: "Belarus", code: "BY", phoneCode: "+375" },
  { name: "Belgium", code: "BE", phoneCode: "+32" },
  { name: "Belize", code: "BZ", phoneCode: "+501" },
  { name: "Benin", code: "BJ", phoneCode: "+229" },
  { name: "Bermuda", code: "BM", phoneCode: "+1-441" },
  { name: "Bhutan", code: "BT", phoneCode: "+975" },
  { name: "Bolivia", code: "BO", phoneCode: "+591" },
  { name: "Bosnia and Herzegovina", code: "BA", phoneCode: "+387" },
  { name: "Botswana", code: "BW", phoneCode: "+267" },
  { name: "Brazil", code: "BR", phoneCode: "+55" },
  { name: "British Indian Ocean Territory", code: "IO", phoneCode: "+246" },
  { name: "British Virgin Islands", code: "VG", phoneCode: "+1-284" },
  { name: "Brunei", code: "BN", phoneCode: "+673" },
  { name: "Bulgaria", code: "BG", phoneCode: "+359" },
  { name: "Burkina Faso", code: "BF", phoneCode: "+226" },
  { name: "Burundi", code: "BI", phoneCode: "+257" },
  { name: "Cambodia", code: "KH", phoneCode: "+855" },
  { name: "Cameroon", code: "CM", phoneCode: "+237" },
  { name: "Canada", code: "CA", phoneCode: "+1" },
  { name: "Cape Verde", code: "CV", phoneCode: "+238" },
  { name: "Cayman Islands", code: "KY", phoneCode: "+1-345" },
  { name: "Central African Republic", code: "CF", phoneCode: "+236" },
  { name: "Chad", code: "TD", phoneCode: "+235" },
  { name: "Chile", code: "CL", phoneCode: "+56" },
  { name: "China", code: "CN", phoneCode: "+86" },
  { name: "Christmas Island", code: "CX", phoneCode: "+61" },
  { name: "Cocos Islands", code: "CC", phoneCode: "+61" },
  { name: "Colombia", code: "CO", phoneCode: "+57" },
  { name: "Comoros", code: "KM", phoneCode: "+269" },
  { name: "Cook Islands", code: "CK", phoneCode: "+682" },
  { name: "Costa Rica", code: "CR", phoneCode: "+506" },
  { name: "Croatia", code: "HR", phoneCode: "+385" },
  { name: "Cuba", code: "CU", phoneCode: "+53" },
  { name: "Curacao", code: "CW", phoneCode: "+599" },
  { name: "Cyprus", code: "CY", phoneCode: "+357" },
  { name: "Czech Republic", code: "CZ", phoneCode: "+420" },
  { name: "Democratic Republic of the Congo", code: "CD", phoneCode: "+243" },
  { name: "Denmark", code: "DK", phoneCode: "+45" },
  { name: "Djibouti", code: "DJ", phoneCode: "+253" },
  { name: "Dominica", code: "DM", phoneCode: "+1-767" },
  {
    name: "Dominican Republic",
    code: "DO",
    phoneCode: "+1-809, +1-829, +1-849",
  },
  { name: "East Timor", code: "TL", phoneCode: "+670" },
  { name: "Ecuador", code: "EC", phoneCode: "+593" },
  { name: "Egypt", code: "EG", phoneCode: "+20" },
  { name: "El Salvador", code: "SV", phoneCode: "+503" },
  { name: "Equatorial Guinea", code: "GQ", phoneCode: "+240" },
  { name: "Eritrea", code: "ER", phoneCode: "+291" },
  { name: "Estonia", code: "EE", phoneCode: "+372" },
  { name: "Ethiopia", code: "ET", phoneCode: "+251" },
  { name: "Falkland Islands", code: "FK", phoneCode: "+500" },
  { name: "Faroe Islands", code: "FO", phoneCode: "+298" },
  { name: "Fiji", code: "FJ", phoneCode: "+679" },
  { name: "Finland", code: "FI", phoneCode: "+358" },
  { name: "France", code: "FR", phoneCode: "+33" },
  { name: "French Polynesia", code: "PF", phoneCode: "+689" },
  { name: "Gabon", code: "GA", phoneCode: "+241" },
  { name: "Gambia", code: "GM", phoneCode: "+220" },
  { name: "Georgia", code: "GE", phoneCode: "+995" },
  { name: "Germany", code: "DE", phoneCode: "+49" },
  { name: "Ghana", code: "GH", phoneCode: "+233" },
  { name: "Gibraltar", code: "GI", phoneCode: "+350" },
  { name: "Greece", code: "GR", phoneCode: "+30" },
  { name: "Greenland", code: "GL", phoneCode: "+299" },
  { name: "Grenada", code: "GD", phoneCode: "+1-473" },
  { name: "Guam", code: "GU", phoneCode: "+1-671" },
  { name: "Guatemala", code: "GT", phoneCode: "+502" },
  { name: "Guernsey", code: "GG", phoneCode: "+44-1481" },
  { name: "Guinea", code: "GN", phoneCode: "+224" },
  { name: "Guinea-Bissau", code: "GW", phoneCode: "+245" },
  { name: "Guyana", code: "GY", phoneCode: "+592" },
  { name: "Haiti", code: "HT", phoneCode: "+509" },
  { name: "Honduras", code: "HN", phoneCode: "+504" },
  { name: "Hong Kong", code: "HK", phoneCode: "+852" },
  { name: "Hungary", code: "HU", phoneCode: "+36" },
  { name: "Iceland", code: "IS", phoneCode: "+354" },
  { name: "India", code: "IN", phoneCode: "+91" },
  { name: "Indonesia", code: "ID", phoneCode: "+62" },
  { name: "Iran", code: "IR", phoneCode: "+98" },
  { name: "Iraq", code: "IQ", phoneCode: "+964" },
  { name: "Ireland", code: "IE", phoneCode: "+353" },
  { name: "Isle of Man", code: "IM", phoneCode: "+44-1624" },
  { name: "Israel", code: "IL", phoneCode: "+972" },
  { name: "Italy", code: "IT", phoneCode: "+39" },
  { name: "Ivory Coast", code: "CI", phoneCode: "+225" },
  { name: "Jamaica", code: "JM", phoneCode: "+1-876" },
  { name: "Japan", code: "JP", phoneCode: "+81" },
  { name: "Jersey", code: "JE", phoneCode: "+44-1534" },
  { name: "Jordan", code: "JO", phoneCode: "+962" },
  { name: "Kazakhstan", code: "KZ", phoneCode: "+7" },
  { name: "Kenya", code: "KE", phoneCode: "+254" },
  { name: "Kiribati", code: "KI", phoneCode: "+686" },
  { name: "Kosovo", code: "XK", phoneCode: "+383" },
  { name: "Kuwait", code: "KW", phoneCode: "+965" },
  { name: "Kyrgyzstan", code: "KG", phoneCode: "+996" },
  { name: "Laos", code: "LA", phoneCode: "+856" },
  { name: "Latvia", code: "LV", phoneCode: "+371" },
  { name: "Lebanon", code: "LB", phoneCode: "+961" },
  { name: "Lesotho", code: "LS", phoneCode: "+266" },
  { name: "Liberia", code: "LR", phoneCode: "+231" },
  { name: "Libya", code: "LY", phoneCode: "+218" },
  { name: "Liechtenstein", code: "LI", phoneCode: "+423" },
  { name: "Lithuania", code: "LT", phoneCode: "+370" },
  { name: "Luxembourg", code: "LU", phoneCode: "+352" },
  { name: "Macau", code: "MO", phoneCode: "+853" },
  { name: "Macedonia", code: "MK", phoneCode: "+389" },
  { name: "Madagascar", code: "MG", phoneCode: "+261" },
  { name: "Malawi", code: "MW", phoneCode: "+265" },
  { name: "Malaysia", code: "MY", phoneCode: "+60" },
  { name: "Maldives", code: "MV", phoneCode: "+960" },
  { name: "Mali", code: "ML", phoneCode: "+223" },
  { name: "Malta", code: "MT", phoneCode: "+356" },
  { name: "Marshall Islands", code: "MH", phoneCode: "+692" },
  { name: "Mauritania", code: "MR", phoneCode: "+222" },
  { name: "Mauritius", code: "MU", phoneCode: "+230" },
  { name: "Mexico", code: "MX", phoneCode: "+52" },
  { name: "Micronesia", code: "FM", phoneCode: "+691" },
  { name: "Moldova", code: "MD", phoneCode: "+373" },
  { name: "Monaco", code: "MC", phoneCode: "+377" },
  { name: "Mongolia", code: "MN", phoneCode: "+976" },
  { name: "Montenegro", code: "ME", phoneCode: "+382" },
  { name: "Montserrat", code: "MS", phoneCode: "+1-664" },
  { name: "Morocco", code: "MA", phoneCode: "+212" },
  { name: "Mozambique", code: "MZ", phoneCode: "+258" },
  { name: "Myanmar", code: "MM", phoneCode: "+95" },
  { name: "Namibia", code: "NA", phoneCode: "+264" },
  { name: "Nauru", code: "NR", phoneCode: "+674" },
  { name: "Nepal", code: "NP", phoneCode: "+977" },
  { name: "Netherlands", code: "NL", phoneCode: "+31" },
  { name: "New Caledonia", code: "NC", phoneCode: "+687" },
  { name: "New Zealand", code: "NZ", phoneCode: "+64" },
  { name: "Nicaragua", code: "NI", phoneCode: "+505" },
  { name: "Niger", code: "NE", phoneCode: "+227" },
  { name: "Nigeria", code: "NG", phoneCode: "+234" },
  { name: "Niue", code: "NU", phoneCode: "+683" },
  { name: "North Korea", code: "KP", phoneCode: "+850" },
  { name: "Northern Mariana Islands", code: "MP", phoneCode: "+1-670" },
  { name: "Norway", code: "NO", phoneCode: "+47" },
  { name: "Oman", code: "OM", phoneCode: "+968" },
  { name: "Pakistan", code: "PK", phoneCode: "+92" },
  { name: "Palau", code: "PW", phoneCode: "+680" },
  { name: "Palestine", code: "PS", phoneCode: "+970" },
  { name: "Panama", code: "PA", phoneCode: "+507" },
  { name: "Papua New Guinea", code: "PG", phoneCode: "+675" },
  { name: "Paraguay", code: "PY", phoneCode: "+595" },
  { name: "Peru", code: "PE", phoneCode: "+51" },
  { name: "Philippines", code: "PH", phoneCode: "+63" },
  { name: "Pitcairn", code: "PN", phoneCode: "+64" },
  { name: "Poland", code: "PL", phoneCode: "+48" },
  { name: "Portugal", code: "PT", phoneCode: "+351" },
  { name: "Puerto Rico", code: "PR", phoneCode: "+1-787, +1-939" },
  { name: "Qatar", code: "QA", phoneCode: "+974" },
  { name: "Republic of the Congo", code: "CG", phoneCode: "+242" },
  { name: "Reunion", code: "RE", phoneCode: "+262" },
  { name: "Romania", code: "RO", phoneCode: "+40" },
  { name: "Russia", code: "RU", phoneCode: "+7" },
  { name: "Rwanda", code: "RW", phoneCode: "+250" },
  { name: "Saint Barthelemy", code: "BL", phoneCode: "+590" },
  { name: "Saint Helena", code: "SH", phoneCode: "+290" },
  { name: "Saint Kitts and Nevis", code: "KN", phoneCode: "+1-869" },
  { name: "Saint Lucia", code: "LC", phoneCode: "+1-758" },
  { name: "Saint Martin", code: "MF", phoneCode: "+590" },
  { name: "Saint Pierre and Miquelon", code: "PM", phoneCode: "+508" },
  { name: "Saint Vincent and the Grenadines", code: "VC", phoneCode: "+1-784" },
  { name: "Samoa", code: "WS", phoneCode: "+685" },
  { name: "San Marino", code: "SM", phoneCode: "+378" },
  { name: "Sao Tome and Principe", code: "ST", phoneCode: "+239" },
  { name: "Saudi Arabia", code: "SA", phoneCode: "+966" },
  { name: "Senegal", code: "SN", phoneCode: "+221" },
  { name: "Serbia", code: "RS", phoneCode: "+381" },
  { name: "Seychelles", code: "SC", phoneCode: "+248" },
  { name: "Sierra Leone", code: "SL", phoneCode: "+232" },
  { name: "Singapore", code: "SG", phoneCode: "+65" },
  { name: "Sint Maarten", code: "SX", phoneCode: "+1-721" },
  { name: "Slovakia", code: "SK", phoneCode: "+421" },
  { name: "Slovenia", code: "SI", phoneCode: "+386" },
  { name: "Solomon Islands", code: "SB", phoneCode: "+677" },
  { name: "Somalia", code: "SO", phoneCode: "+252" },
  { name: "South Africa", code: "ZA", phoneCode: "+27" },
  { name: "South Korea", code: "KR", phoneCode: "+82" },
  { name: "South Sudan", code: "SS", phoneCode: "+211" },
  { name: "Spain", code: "ES", phoneCode: "+34" },
  { name: "Sri Lanka", code: "LK", phoneCode: "+94" },
  { name: "Sudan", code: "SD", phoneCode: "+249" },
  { name: "Suriname", code: "SR", phoneCode: "+597" },
  { name: "Svalbard and Jan Mayen", code: "SJ", phoneCode: "+47" },
  { name: "Swaziland", code: "SZ", phoneCode: "+268" },
  { name: "Sweden", code: "SE", phoneCode: "+46" },
  { name: "Switzerland", code: "CH", phoneCode: "+41" },
  { name: "Syria", code: "SY", phoneCode: "+963" },
  { name: "Taiwan", code: "TW", phoneCode: "+886" },
  { name: "Tajikistan", code: "TJ", phoneCode: "+992" },
  { name: "Tanzania", code: "TZ", phoneCode: "+255" },
  { name: "Thailand", code: "TH", phoneCode: "+66" },
  { name: "Togo", code: "TG", phoneCode: "+228" },
  { name: "Tokelau", code: "TK", phoneCode: "+690" },
  { name: "Tonga", code: "TO", phoneCode: "+676" },
  { name: "Trinidad and Tobago", code: "TT", phoneCode: "+1-868" },
  { name: "Tunisia", code: "TN", phoneCode: "+216" },
  { name: "Turkey", code: "TR", phoneCode: "+90" },
  { name: "Turkmenistan", code: "TM", phoneCode: "+993" },
  { name: "Turks and Caicos Islands", code: "TC", phoneCode: "+1-649" },
  { name: "Tuvalu", code: "TV", phoneCode: "+688" },
  { name: "U.S. Virgin Islands", code: "VI", phoneCode: "+1-340" },
  { name: "Uganda", code: "UG", phoneCode: "+256" },
  { name: "Ukraine", code: "UA", phoneCode: "+380" },
  { name: "United Arab Emirates", code: "AE", phoneCode: "+971" },
  { name: "United Kingdom", code: "GB", phoneCode: "+44" },
  { name: "United States", code: "US", phoneCode: "+1" },
  { name: "Uruguay", code: "UY", phoneCode: "+598" },
  { name: "Uzbekistan", code: "UZ", phoneCode: "+998" },
  { name: "Vanuatu", code: "VU", phoneCode: "+678" },
  { name: "Vatican", code: "VA", phoneCode: "+379" },
  { name: "Venezuela", code: "VE", phoneCode: "+58" },
  { name: "Vietnam", code: "VN", phoneCode: "+84" },
  { name: "Wallis and Futuna", code: "WF", phoneCode: "+681" },
  { name: "Western Sahara", code: "EH", phoneCode: "+212" },
  { name: "Yemen", code: "YE", phoneCode: "+967" },
  { name: "Zambia", code: "ZM", phoneCode: "+260" },
  { name: "Zimbabwe", code: "ZW", phoneCode: "+263" },
];

// export const countries = [
//   { name: "Afghanistan", code: "AF" },
//   { name: "Albania", code: "AL" },
//   { name: "Algeria", code: "DZ" },
//   { name: "American Samoa", code: "AS" },
//   { name: "Andorra", code: "AD" },
//   { name: "Angola", code: "AO" },
//   { name: "Anguilla", code: "AI" },
//   { name: "Antarctica", code: "AQ" },
//   { name: "Antigua and Barbuda", code: "AG" },
//   { name: "Argentina", code: "AR" },
//   { name: "Armenia", code: "AM" },
//   { name: "Aruba", code: "AW" },
//   { name: "Australia", code: "AU" },
//   { name: "Austria", code: "AT" },
//   { name: "Azerbaijan", code: "AZ" },
//   { name: "Bahamas", code: "BS" },
//   { name: "Bahrain", code: "BH" },
//   { name: "Bangladesh", code: "BD" },
//   { name: "Barbados", code: "BB" },
//   { name: "Belarus", code: "BY" },
//   { name: "Belgium", code: "BE" },
//   { name: "Belize", code: "BZ" },
//   { name: "Benin", code: "BJ" },
//   { name: "Bermuda", code: "BM" },
//   { name: "Bhutan", code: "BT" },
//   { name: "Bolivia", code: "BO" },
//   { name: "Bosnia and Herzegovina", code: "BA" },
//   { name: "Botswana", code: "BW" },
//   { name: "Brazil", code: "BR" },
//   { name: "British Indian Ocean Territory", code: "IO" },
//   { name: "British Virgin Islands", code: "VG" },
//   { name: "Brunei", code: "BN" },
//   { name: "Bulgaria", code: "BG" },
//   { name: "Burkina Faso", code: "BF" },
//   { name: "Burundi", code: "BI" },
//   { name: "Cambodia", code: "KH" },
//   { name: "Cameroon", code: "CM" },
//   { name: "Canada", code: "CA" },
//   { name: "Cape Verde", code: "CV" },
//   { name: "Cayman Islands", code: "KY" },
//   { name: "Central African Republic", code: "CF" },
//   { name: "Chad", code: "TD" },
//   { name: "Chile", code: "CL" },
//   { name: "China", code: "CN" },
//   { name: "Christmas Island", code: "CX" },
//   { name: "Cocos Islands", code: "CC" },
//   { name: "Colombia", code: "CO" },
//   { name: "Comoros", code: "KM" },
//   { name: "Cook Islands", code: "CK" },
//   { name: "Costa Rica", code: "CR" },
//   { name: "Croatia", code: "HR" },
//   { name: "Cuba", code: "CU" },
//   { name: "Curacao", code: "CW" },
//   { name: "Cyprus", code: "CY" },
//   { name: "Czech Republic", code: "CZ" },
//   { name: "Democratic Republic of the Congo", code: "CD" },
//   { name: "Denmark", code: "DK" },
//   { name: "Djibouti", code: "DJ" },
//   { name: "Dominica", code: "DM" },
//   { name: "Dominican Republic", code: "DO" },
//   { name: "East Timor", code: "TL" },
//   { name: "Ecuador", code: "EC" },
//   { name: "Egypt", code: "EG" },
//   { name: "El Salvador", code: "SV" },
//   { name: "Equatorial Guinea", code: "GQ" },
//   { name: "Eritrea", code: "ER" },
//   { name: "Estonia", code: "EE" },
//   { name: "Ethiopia", code: "ET" },
//   { name: "Falkland Islands", code: "FK" },
//   { name: "Faroe Islands", code: "FO" },
//   { name: "Fiji", code: "FJ" },
//   { name: "Finland", code: "FI" },
//   { name: "France", code: "FR" },
//   { name: "French Polynesia", code: "PF" },
//   { name: "Gabon", code: "GA" },
//   { name: "Gambia", code: "GM" },
//   { name: "Georgia", code: "GE" },
//   { name: "Germany", code: "DE" },
//   { name: "Ghana", code: "GH" },
//   { name: "Gibraltar", code: "GI" },
//   { name: "Greece", code: "GR" },
//   { name: "Greenland", code: "GL" },
//   { name: "Grenada", code: "GD" },
//   { name: "Guam", code: "GU" },
//   { name: "Guatemala", code: "GT" },
//   { name: "Guernsey", code: "GG" },
//   { name: "Guinea", code: "GN" },
//   { name: "Guinea-Bissau", code: "GW" },
//   { name: "Guyana", code: "GY" },
//   { name: "Haiti", code: "HT" },
//   { name: "Honduras", code: "HN" },
//   { name: "Hong Kong", code: "HK" },
//   { name: "Hungary", code: "HU" },
//   { name: "Iceland", code: "IS" },
//   { name: "India", code: "IN" },
//   { name: "Indonesia", code: "ID" },
//   { name: "Iran", code: "IR" },
//   { name: "Iraq", code: "IQ" },
//   { name: "Ireland", code: "IE" },
//   { name: "Isle of Man", code: "IM" },
//   { name: "Israel", code: "IL" },
//   { name: "Italy", code: "IT" },
//   { name: "Ivory Coast", code: "CI" },
//   { name: "Jamaica", code: "JM" },
//   { name: "Japan", code: "JP" },
//   { name: "Jersey", code: "JE" },
//   { name: "Jordan", code: "JO" },
//   { name: "Kazakhstan", code: "KZ" },
//   { name: "Kenya", code: "KE" },
//   { name: "Kiribati", code: "KI" },
//   { name: "Kosovo", code: "XK" },
//   { name: "Kuwait", code: "KW" },
//   { name: "Kyrgyzstan", code: "KG" },
//   { name: "Laos", code: "LA" },
//   { name: "Latvia", code: "LV" },
//   { name: "Lebanon", code: "LB" },
//   { name: "Lesotho", code: "LS" },
//   { name: "Liberia", code: "LR" },
//   { name: "Libya", code: "LY" },
//   { name: "Liechtenstein", code: "LI" },
//   { name: "Lithuania", code: "LT" },
//   { name: "Luxembourg", code: "LU" },
//   { name: "Macau", code: "MO" },
//   { name: "Macedonia", code: "MK" },
//   { name: "Madagascar", code: "MG" },
//   { name: "Malawi", code: "MW" },
//   { name: "Malaysia", code: "MY" },
//   { name: "Maldives", code: "MV" },
//   { name: "Mali", code: "ML" },
//   { name: "Malta", code: "MT" },
//   { name: "Marshall Islands", code: "MH" },
//   { name: "Mauritania", code: "MR" },
//   { name: "Mauritius", code: "MU" },
//   { name: "Mexico", code: "MX" },
//   { name: "Micronesia", code: "FM" },
//   { name: "Moldova", code: "MD" },
//   { name: "Monaco", code: "MC" },
//   { name: "Mongolia", code: "MN" },
//   { name: "Montenegro", code: "ME" },
//   { name: "Montserrat", code: "MS" },
//   { name: "Morocco", code: "MA" },
//   { name: "Mozambique", code: "MZ" },
//   { name: "Myanmar", code: "MM" },
//   { name: "Namibia", code: "NA" },
//   { name: "Nauru", code: "NR" },
//   { name: "Nepal", code: "NP" },
//   { name: "Netherlands", code: "NL" },
//   { name: "New Caledonia", code: "NC" },
//   { name: "New Zealand", code: "NZ" },
//   { name: "Nicaragua", code: "NI" },
//   { name: "Niger", code: "NE" },
//   { name: "Nigeria", code: "NG" },
//   { name: "Niue", code: "NU" },
//   { name: "North Korea", code: "KP" },
//   { name: "Northern Mariana Islands", code: "MP" },
//   { name: "Norway", code: "NO" },
//   { name: "Oman", code: "OM" },
//   { name: "Pakistan", code: "PK" },
//   { name: "Palau", code: "PW" },
//   { name: "Palestine", code: "PS" },
//   { name: "Panama", code: "PA" },
//   { name: "Papua New Guinea", code: "PG" },
//   { name: "Paraguay", code: "PY" },
//   { name: "Peru", code: "PE" },
//   { name: "Philippines", code: "PH" },
//   { name: "Pitcairn", code: "PN" },
//   { name: "Poland", code: "PL" },
//   { name: "Portugal", code: "PT" },
//   { name: "Puerto Rico", code: "PR" },
//   { name: "Qatar", code: "QA" },
//   { name: "Republic of the Congo", code: "CG" },
//   { name: "Reunion", code: "RE" },
//   { name: "Romania", code: "RO" },
//   { name: "Russia", code: "RU" },
//   { name: "Rwanda", code: "RW" },
//   { name: "Saint Barthelemy", code: "BL" },
//   { name: "Saint Helena", code: "SH" },
//   { name: "Saint Kitts and Nevis", code: "KN" },
//   { name: "Saint Lucia", code: "LC" },
//   { name: "Saint Martin", code: "MF" },
//   { name: "Saint Pierre and Miquelon", code: "PM" },
//   { name: "Saint Vincent and the Grenadines", code: "VC" },
//   { name: "Samoa", code: "WS" },
//   { name: "San Marino", code: "SM" },
//   { name: "Sao Tome and Principe", code: "ST" },
//   { name: "Saudi Arabia", code: "SA" },
//   { name: "Senegal", code: "SN" },
//   { name: "Serbia", code: "RS" },
//   { name: "Seychelles", code: "SC" },
//   { name: "Sierra Leone", code: "SL" },
//   { name: "Singapore", code: "SG" },
//   { name: "Sint Maarten", code: "SX" },
//   { name: "Slovakia", code: "SK" },
//   { name: "Slovenia", code: "SI" },
//   { name: "Solomon Islands", code: "SB" },
//   { name: "Somalia", code: "SO" },
//   { name: "South Africa", code: "ZA" },
//   { name: "South Korea", code: "KR" },
//   { name: "South Sudan", code: "SS" },
//   { name: "Spain", code: "ES" },
//   { name: "Sri Lanka", code: "LK" },
//   { name: "Sudan", code: "SD" },
//   { name: "Suriname", code: "SR" },
//   { name: "Svalbard and Jan Mayen", code: "SJ" },
//   { name: "Swaziland", code: "SZ" },
//   { name: "Sweden", code: "SE" },
//   { name: "Switzerland", code: "CH" },
//   { name: "Syria", code: "SY" },
//   { name: "Taiwan", code: "TW" },
//   { name: "Tajikistan", code: "TJ" },
//   { name: "Tanzania", code: "TZ" },
//   { name: "Thailand", code: "TH" },
//   { name: "Togo", code: "TG" },
//   { name: "Tokelau", code: "TK" },
//   { name: "Tonga", code: "TO" },
//   { name: "Trinidad and Tobago", code: "TT" },
//   { name: "Tunisia", code: "TN" },
//   { name: "Turkey", code: "TR" },
//   { name: "Turkmenistan", code: "TM" },
//   { name: "Turks and Caicos Islands", code: "TC" },
//   { name: "Tuvalu", code: "TV" },
//   { name: "U.S. Virgin Islands", code: "VI" },
//   { name: "Uganda", code: "UG" },
//   { name: "Ukraine", code: "UA" },
//   { name: "United Arab Emirates", code: "AE" },
//   { name: "United Kingdom", code: "GB" },
//   { name: "United States", code: "US" },
//   { name: "Uruguay", code: "UY" },
//   { name: "Uzbekistan", code: "UZ" },
//   { name: "Vanuatu", code: "VU" },
//   { name: "Vatican", code: "VA" },
//   { name: "Venezuela", code: "VE" },
//   { name: "Vietnam", code: "VN" },
//   { name: "Wallis and Futuna", code: "WF" },
//   { name: "Western Sahara", code: "EH" },
//   { name: "Yemen", code: "YE" },
//   { name: "Zambia", code: "ZM" },
//   { name: "Zimbabwe", code: "ZW" },
// ];
